[font]
offset = { x = 1 , y = 4 }
size = 11
[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[window]
# decorations = "none"
opacity = 0.95
padding = { x = 12, y = 12 }

[window.dimensions]
columns = 140
lines = 50

[terminal]
