tap "homebrew/bundle"
tap "homebrew/services"
tap "shivammathur/extensions"
tap "shivammathur/php"
brew "composer"
brew "fontforge"
brew "gh"
brew "git-delta"
brew "gitui"
brew "mailpit"
brew "mysql"
brew "neovim"
brew "php@8.3", link: true
brew "pipx"
brew "postgresql@14", restart_service: true
brew "redis", restart_service: true
brew "starship"
brew "shivammathur/extensions/redis@8.3"
