#!/usr/bin/env sh

###################
# Global settings #
###################
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off
# move mouse to focused window
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             second_child
# floating windows always stay on top
yabai -m config window_topmost               on
# enable borders
yabai -m config window_border                on
# no idea what this is
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
yabai -m config auto_balance                 off

#################
# Setup spacing #
#################
yabai -m config layout                       bsp
yabai -m config top_padding                  8    
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

################
# SIP Required #
################
# prevent border from being under the active window
yabai -m config active_window_border_topmost on
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xFFFFA726
yabai -m config normal_window_border_color   0xFF0097A7


####################
# Rule and Signals #
####################
# set floating app rules 
yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off

# set dedicated spaces for different apps
yabai -m space 2 --label messaging 
yabai -m rule --add app="^Telegram$" space 2 
yabai -m rule --add app="^WhatsApp$" space 2 

yabai -m space 3 --label mail 
yabai -m rule --add app="^Microsoft Outlook$" space 3
yabai -m rule --add app="^Mail$" space 3

yabai -m space 4 --label comms 
yabai -m rule --add app="^Discord$" space 4 
yabai -m rule --add app="^Microsoft Teams$" space 4 

yabai -m space 5 --label music
yabai -m rule --add app="^Spotify$" space 5 

yabai -m space 6 --label dev 
yabai -m rule --add app="^Code$" space 6
